substitutions:
  _REGION: us-central1
  _REPO: pdf-renderer
  _SERVICE: pdf-renderer

images:
- $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/pdf-renderer:$SHORT_SHA

steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/pdf-renderer:$SHORT_SHA','.']

- name: gcr.io/cloud-builders/docker
  args: ['push','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/pdf-renderer:$SHORT_SHA']

- name: gcr.io/cloud-builders/gcloud
  args:
    - run
    - deploy
    - $_SERVICE
    - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/pdf-renderer:$SHORT_SHA
    - --region=$_REGION
    - --allow-unauthenticated
    - --port=8080
    - --cpu=1
    - --memory=1Gi
    - --set-secrets=RENDER_TOKEN=RENDER_TOKEN:latest
    - --set-env-vars=NODE_ENV=production
